### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by andre-brdoch** [andre-brdoch/advent-of-code-2022#1]
- [x]  read input in `src/index` and pass it into the solution functions
- [x] move solutions into separate folders, eg: `day-01/solution-01.ts`
- [x] move input files into the day folders
- [x] add markdown files for all days with the task
- [x] update readme: link, goals, requirements, tasks completed, stars collected
- [x] extract types
- [ ] support running all days
- [ ] show more helpful error if an invalid day was passed
- [ ] print visuals
- [ ] change folder structure: group data by test/prod 

# Day improvements

## 21

Remove timeout, and resolve properly with promise. Also see if you can use the same solution for pt 1 and 2, its a bit messy now.

## 16

Not working right now, I think it required `NODE_OPTIONS=--max_old_space_size=8192` flag
